"""WPS rule messages keyed by code."""

MESSAGES: dict[str, str] = {
    'WPS000': 'Internal linting error (reserved; never emitted by rules)',
    'WPS100': 'Forbid blacklisted module names',
    'WPS101': 'Forbid magic module names',
    'WPS102': 'Forbid module names that do not match pattern',
    'WPS110': 'Forbid blacklisted variable names',
    'WPS111': 'Forbid short names',
    'WPS112': 'Forbid private name pattern',
    'WPS113': 'Forbid same alias as original in imports',
    'WPS114': 'Forbid underscored numbers in names',
    'WPS115': 'Require snake_case for class attributes',
    'WPS116': 'Forbid consecutive underscores in names',
    'WPS117': 'Forbid reserved self/cls/mcs as variables',
    'WPS118': 'Forbid long names',
    'WPS119': 'Forbid unicode names',
    'WPS120': 'Forbid unnecessary trailing underscore',
    'WPS121': 'Forbid using variables marked unused',
    'WPS122': 'Forbid explicit unused variables',
    'WPS123': 'Forbid unused variables with multiple underscores',
    'WPS124': 'Forbid unreadable names',
    'WPS125': 'Forbid shadowing builtins',
    'WPS200': 'Forbid modules with complex lines (Jones)',
    'WPS201': 'Forbid too many imports',
    'WPS202': 'Forbid too many module members',
    'WPS203': 'Forbid too many imported names',
    'WPS204': 'Forbid overused expressions',
    'WPS210': 'Forbid too many local variables',
    'WPS211': 'Forbid too many arguments',
    'WPS212': 'Forbid too many returns',
    'WPS213': 'Forbid too many expressions',
    'WPS214': 'Forbid too many methods',
    'WPS215': 'Forbid too many base classes',
    'WPS216': 'Forbid too many decorators',
    'WPS217': 'Forbid too many awaits',
    'WPS218': 'Forbid too many asserts',
    'WPS219': 'Forbid too deep access',
    'WPS220': 'Forbid too deep nesting',
    'WPS221': 'Forbid complex lines',
    'WPS222': 'Forbid too many conditions',
    'WPS223': 'Forbid too many elifs',
    'WPS224': 'Forbid too many fors in comprehension',
    'WPS225': 'Forbid too many except cases',
    'WPS226': 'Forbid overused string literals',
    'WPS227': 'Forbid too long output tuples',
    'WPS228': 'Forbid too long compares',
    'WPS229': 'Forbid too long try body',
    'WPS230': 'Forbid too many public attributes',
    'WPS231': 'Forbid high cognitive complexity',
    'WPS232': 'Forbid high average cognitive complexity',
    'WPS233': 'Forbid too long call chains',
    'WPS234': 'Forbid complex annotations',
    'WPS235': 'Forbid too many import-from members',
    'WPS236': 'Forbid too long tuple unpack',
    'WPS237': 'Forbid complex f-strings',
    'WPS238': 'Forbid too many raises',
    'WPS239': 'Forbid too many except exceptions',
    'WPS240': 'Forbid too many type params',
    'WPS241': 'Forbid too many match subjects',
    'WPS242': 'Forbid too many match cases',
    'WPS243': 'Forbid too long finally body',
    'WPS300': 'Forbid imports relative to the current folder.',
    'WPS301': 'Forbid imports like import os.path.',
    'WPS302': 'Forbid u string prefix.',
    'WPS303': 'Forbid underscores (_) in numbers.',
    'WPS304': 'Forbid partial floats like .05 or 23..',
    'WPS305': 'Forbid f strings.',
    'WPS306': 'Forbid writing explicit object base class.',
    'WPS307': 'Forbid multiple if statements inside list comprehensions.',
    'WPS308': 'Forbid comparing between two literals.',
    'WPS309': 'Forbid comparisons where the argument doesn\'t come first.',
    'WPS310': 'Forbid uppercase X, O, B, and E in numbers.',
    'WPS311': 'Forbid comparisons with multiple in checks.',
    'WPS312': 'Forbid comparisons of a variable to itself.',
    'WPS313': 'Enforce separation of parenthesis from keywords with spaces.',
    'WPS314': 'Forbid using if or match statements that use invalid conditionals.',
    'WPS315': 'Forbid extra object in parent classes list.',
    'WPS316': 'Forbid multiple assignment targets for context managers.',
    'WPS317': 'Forbid incorrect indentation for parameters.',
    'WPS318': 'Forbid extra indentation.',
    'WPS319': 'Forbid brackets in the wrong position.',
    'WPS320': 'Forbid multi-line function type annotations.',
    'WPS321': 'Forbid uppercase string modifiers.',
    'WPS322': 'Forbid triple quotes for singleline strings.',
    'WPS323': 'Forbid % formatting on strings.',
    'WPS324': 'Enforce consistent return statements.',
    'WPS325': 'Enforce consistent yield statements.',
    'WPS326': 'Forbid implicit string concatenation.',
    'WPS327': 'Forbid meaningless continue in loops.',
    'WPS328': 'Forbid meaningless nodes.',
    'WPS329': 'Forbid meaningless except cases.',
    'WPS330': 'Forbid unnecessary operators in your code.',
    'WPS331': 'Forbid local variables that are only used in return statements.',
    'WPS332': 'Forbid the use of the walrus operator (:=) in most cases.',
    'WPS333': 'Forbid implicit complex comparison expressions.',
    'WPS334': 'Forbid reversed order complex comparison expressions.',
    'WPS335': 'Forbid wrong for loop iter targets.',
    'WPS336': 'Forbid explicit string concatenation in favour of .format method.',
    'WPS337': 'Forbid multiline conditions.',
    'WPS338': 'Forbid incorrect order of methods inside a class.',
    'WPS339': 'Forbid meaningless zeros.',
    'WPS340': 'Forbid extra + signs in the exponent.',
    'WPS341': 'Forbid letters as hex numbers.',
    'WPS342': 'Forbid \\\\ escape sequences inside regular strings.',
    'WPS343': 'Forbid uppercase complex number suffix.',
    'WPS344': 'Forbid explicit division (or modulo) by zero.',
    'WPS345': 'Forbid meaningless math operations with 0 and 1.',
    'WPS346': 'Forbid double minus operations.',
    'WPS347': 'Forbid imports that may cause confusion outside of the module.',
    'WPS348': 'Forbid starting lines with a dot.',
    'WPS349': 'Forbid redundant components in a subscript\'s slice.',
    'WPS350': 'Enforce using augmented assign pattern.',
    'WPS351': 'Forbid unnecessary literals in your code.',
    'WPS352': 'Forbid multiline loops.',
    'WPS353': 'Forbid yield from with several nodes.',
    'WPS354': 'Forbid consecutive yield expressions.',
    'WPS355': 'Forbid useless blank lines before and after brackets.',
    'WPS356': 'Forbid unnecessary iterable unpacking.',
    'WPS357': 'Forbid using \\r (carriage return) in line breaks.',
    'WPS358': 'Forbid using float zeros: 0.0.',
    'WPS359': 'Forbids to unpack iterable objects to lists.',
    'WPS360': 'Forbid the use of raw strings when there is no backslash in the string.',
    'WPS361': 'Forbids inconsistent newlines in comprehensions.',
    'WPS362': 'Forbid assignment to a subscript slice.',
    'WPS363': 'Forbid raising SystemExit.',
    'WPS364': 'Forbid using not a in b instead of a not in b.',
    'WPS365': 'Some match statements can be simplified to if statements.',
    'WPS366': 'Forbid meaningless boolean operations.',
    'WPS400': 'Restrict various control (such as magic) comments.',
    'WPS401': 'Forbid empty doc comments (#:).',
    'WPS402': 'Forbid too many # noqa comments.',
    'WPS403': 'Forbid too many # pragma: no cover comments.',
    'WPS404': 'Forbid complex defaults.',
    'WPS405': 'Forbid anything other than ast.Name to define loop variables.',
    'WPS406': 'Forbid anything other than ast.Name to define contexts.',
    'WPS407': 'Forbid mutable constants on a module level.',
    'WPS408': 'Forbid using the same logical conditions in one expression.',
    'WPS409': 'Forbid heterogeneous operators in one comparison.',
    'WPS410': 'Forbid some module-level variables.',
    'WPS411': 'Forbid empty modules.',
    'WPS412': 'Forbid logic inside __init__ module.',
    'WPS413': 'Forbid __getattr__ and __dir__ module magic methods.',
    'WPS414': 'Forbid tuple unpacking with side-effects.',
    'WPS415': 'Forbid the same exception class in multiple except blocks.',
    'WPS416': 'Forbid yield keyword inside comprehensions.',
    'WPS417': 'Forbid duplicate items in hashes.',
    'WPS418': 'Forbid exceptions inherited from BaseException.',
    'WPS419': 'Forbid multiple returning paths with try / except case.',
    'WPS420': 'Forbid some python keywords.',
    'WPS421': 'Forbid calling some built-in functions.',
    'WPS422': 'Forbid __future__ imports.',
    'WPS423': 'Forbid NotImplemented exception.',
    'WPS424': 'Forbid BaseException exception.',
    'WPS425': 'Forbid booleans as non-keyword parameters.',
    'WPS426': 'Forbid lambda inside loops.',
    'WPS427': 'Forbid unreachable code.',
    'WPS428': 'Forbid statements that do nothing.',
    'WPS429': 'Forbid multiple assignments on the same line.',
    'WPS430': 'Forbid nested functions.',
    'WPS431': 'Forbid nested classes.',
    'WPS432': 'Forbid magic numbers.',
    'WPS433': 'Forbid imports nested in functions.',
    'WPS434': 'Forbid assigning a variable to itself.',
    'WPS435': 'Forbid multiplying lists.',
    'WPS436': 'Forbid importing protected modules.',
    'WPS437': 'Forbid protected attributes and methods.',
    'WPS438': 'Forbid raising StopIteration inside generators.',
    'WPS439': 'Forbid Unicode escape sequences in binary strings.',
    'WPS440': 'Forbid overlapping local and block variables.',
    'WPS441': 'Forbid control variables after the block body.',
    'WPS442': 'Forbid shadowing variables from outer scopes.',
    'WPS443': 'Forbid explicit unhashable types of asset items and dict keys.',
    'WPS444': 'Forbid explicit falsely-evaluated conditions with several keywords.',
    'WPS445': 'Forbid incorrectly named keywords in starred dicts.',
    'WPS446': 'Forbid approximate constants.',
    'WPS447': 'Forbid using the alphabet as a string.',
    'WPS448': 'Forbid incorrect order of except.',
    'WPS449': 'Forbid float keys.',
    'WPS450': 'Forbid importing protected objects from modules.',
    'WPS451': 'Forbid positional only or / arguments.',
    'WPS452': 'Forbid break and continue in a finally block.',
    'WPS453': 'Forbid executing a file with shebang incorrectly set.',
    'WPS454': 'Forbid raising Exception or BaseException.',
    'WPS455': 'Forbids using non-trivial expressions as a parameter for except.',
    'WPS456': 'Forbids using float("NaN") construct to generate NaN.',
    'WPS457': 'Forbids use of infinite while True: loops.',
    'WPS458': 'Forbids to import from already imported modules.',
    'WPS459': 'Forbids comparisons with float and complex.',
    'WPS460': 'Forbids to have single element destructuring.',
    'WPS461': 'Forbids to use specific inline ignore violations.',
    'WPS462': 'Forbids direct usage of multiline strings.',
    'WPS463': 'Forbids to have functions starting with get_ without returning a value.',
    'WPS464': 'Forbid empty comments.',
    'WPS465': 'Forbid comparisons between bitwise and boolean expressions.',
    'WPS466': 'Forbid using complex grammar for using decorators.',
    'WPS467': 'Forbid using a bare raise keyword outside of except.',
    'WPS468': 'Forbid using a placeholder (_) with enumerate.',
    'WPS469': 'Forbid raising an exception from itself.',
    'WPS470': 'Forbid kwarg unpacking in class definition.',
    'WPS471': 'Forbid consecutive slices.',
    'WPS472': 'Forbid getting first element using unpacking.',
    'WPS473': 'Limit empty lines in functions or methods body.',
    'WPS474': 'Do not allow importing the same object under different aliases.',
    'WPS475': 'Do not use problematic function parameters.',
    'WPS476': 'Do not use await in for loop.',
    'WPS477': 'Forbid using TypeVarTuple after a TypeVar with default.',
    'WPS478': 'Forbid using non strict slice operations.',
    'WPS479': 'Forbid using multi-line formatted string with single and double quotes.',
    'WPS480': 'Forbid using comments inside formatted strings.',
    'WPS481': 'Found a leaking for loop in a class or module body.',
    'WPS500': 'Forbid`else` without`break` in a loop.',
    'WPS501': 'Forbid`finally` in`try` block without`except` block.',
    'WPS502': 'Forbid simplifiable`if` conditions.',
    'WPS503': 'Forbid useless`else` cases in returning functions.',
    'WPS504': 'Forbid negated conditions together with`else` clause.',
    'WPS505': 'Forbid nested`try` blocks.',
    'WPS506': 'Forbid useless proxy`lambda` expressions.',
    'WPS507': 'Forbid unpythonic zero-length compare.',
    'WPS508': 'Forbid`not` with compare expressions.',
    'WPS509': 'Forbid nesting ternary expressions in certain places.',
    'WPS510': 'Forbid`in` with static containers except`set` nodes.',
    'WPS511': 'Forbid multiple`isinstance` calls on the same variable.',
    'WPS512': 'Forbid multiple`isinstance` calls with single-item tuples.',
    'WPS513': 'Forbid implicit`elif` conditions.',
    'WPS514': 'Forbid multiple equality comparisons with the same variable.',
    'WPS515': 'Forbid`open()` without a context manager.',
    'WPS516': 'Forbid comparing types with`type()` function.',
    'WPS517': 'Forbid useless starred expressions.',
    'WPS518': 'Forbid implicit`enumerate()` calls.',
    'WPS519': 'Forbid implicit`sum()` calls.',
    'WPS520': 'Forbid comparing with explicit falsy constants.',
    'WPS521': 'Forbid comparing values with constants using`is` or`is not`.',
    'WPS522': 'Forbid implicit primitives in the form of`lambda` functions.',
    'WPS523': 'Forbid unpythonic variable swaps.',
    'WPS524': 'Forbid misrefactored self assignment.',
    'WPS525': 'Forbid comparisons where`in` is compared with single item container.',
    'WPS526': 'Forbid`yield` inside`for` loop instead of`yield from`.',
    'WPS527': 'Require tuples as arguments for certain functions.',
    'WPS528': 'Forbid implicit`.items()` iterator.',
    'WPS529': 'Forbid implicit`.get()` dict method.',
    'WPS530': 'Forbid implicit negative indexes.',
    'WPS531': 'Forbid if statements that simply return booleans in functions or methods.',
    'WPS532': 'Forbid ast.Is in ast.Compare.ops when it\'s size is not zero.',
    'WPS533': 'Forbid having duplicate conditions in several`if`//`elif` branches.',
    'WPS534': 'Forbid having useless ternary expressions.',
    'WPS535': 'Forbid having duplicate`case` patterns.',
    'WPS536': 'Forbid extra syntax around`match` like list, set, or dict.',
    'WPS600': 'Forbid subclassing lowercase builtins',
    'WPS601': 'Forbid shadowing class attributes with instance attributes',
    'WPS602': 'Forbid @staticmethod decorator',
    'WPS603': 'Forbid certain magic methods',
    'WPS604': 'Forbid incorrect nodes inside class definitions',
    'WPS605': 'Forbid methods without any arguments',
    'WPS606': 'Forbid non-class base classes',
    'WPS607': 'Forbid incorrect __slots__ definition',
    'WPS608': 'Forbid super() with parameters or outside methods',
    'WPS609': 'Forbid direct magic attribute access',
    'WPS610': 'Forbid certain async magic methods',
    'WPS611': 'Forbid yield inside certain magic methods',
    'WPS612': 'Forbid useless overwritten methods',
    'WPS613': 'Forbid super() with incorrect method access',
    'WPS614': 'Forbid descriptors on regular functions',
    'WPS615': 'Forbid getters and setters in objects',
    'WPS616': 'Forbid bare super() in buggy contexts',
    'WPS617': 'Forbid lambda assigned as attribute',
}

GROUPS: dict[str, str] = {
    'WPS000': 'system',
    'WPS100': 'naming',
    'WPS101': 'naming',
    'WPS102': 'naming',
    'WPS110': 'naming',
    'WPS111': 'naming',
    'WPS112': 'naming',
    'WPS113': 'naming',
    'WPS114': 'naming',
    'WPS115': 'naming',
    'WPS116': 'naming',
    'WPS117': 'naming',
    'WPS118': 'naming',
    'WPS119': 'naming',
    'WPS120': 'naming',
    'WPS121': 'naming',
    'WPS122': 'naming',
    'WPS123': 'naming',
    'WPS124': 'naming',
    'WPS125': 'naming',
    'WPS200': 'complexity',
    'WPS201': 'complexity',
    'WPS202': 'complexity',
    'WPS203': 'complexity',
    'WPS204': 'complexity',
    'WPS210': 'complexity',
    'WPS211': 'complexity',
    'WPS212': 'complexity',
    'WPS213': 'complexity',
    'WPS214': 'complexity',
    'WPS215': 'complexity',
    'WPS216': 'complexity',
    'WPS217': 'complexity',
    'WPS218': 'complexity',
    'WPS219': 'complexity',
    'WPS220': 'complexity',
    'WPS221': 'complexity',
    'WPS222': 'complexity',
    'WPS223': 'complexity',
    'WPS224': 'complexity',
    'WPS225': 'complexity',
    'WPS226': 'complexity',
    'WPS227': 'complexity',
    'WPS228': 'complexity',
    'WPS229': 'complexity',
    'WPS230': 'complexity',
    'WPS231': 'complexity',
    'WPS232': 'complexity',
    'WPS233': 'complexity',
    'WPS234': 'complexity',
    'WPS235': 'complexity',
    'WPS236': 'complexity',
    'WPS237': 'complexity',
    'WPS238': 'complexity',
    'WPS239': 'complexity',
    'WPS240': 'complexity',
    'WPS241': 'complexity',
    'WPS242': 'complexity',
    'WPS243': 'complexity',
    'WPS300': 'consistency',
    'WPS301': 'consistency',
    'WPS302': 'consistency',
    'WPS303': 'consistency',
    'WPS304': 'consistency',
    'WPS305': 'consistency',
    'WPS306': 'consistency',
    'WPS307': 'consistency',
    'WPS308': 'consistency',
    'WPS309': 'consistency',
    'WPS310': 'consistency',
    'WPS311': 'consistency',
    'WPS312': 'consistency',
    'WPS313': 'consistency',
    'WPS314': 'consistency',
    'WPS315': 'consistency',
    'WPS316': 'consistency',
    'WPS317': 'consistency',
    'WPS318': 'consistency',
    'WPS319': 'consistency',
    'WPS320': 'consistency',
    'WPS321': 'consistency',
    'WPS322': 'consistency',
    'WPS323': 'consistency',
    'WPS324': 'consistency',
    'WPS325': 'consistency',
    'WPS326': 'consistency',
    'WPS327': 'consistency',
    'WPS328': 'consistency',
    'WPS329': 'consistency',
    'WPS330': 'consistency',
    'WPS331': 'consistency',
    'WPS332': 'consistency',
    'WPS333': 'consistency',
    'WPS334': 'consistency',
    'WPS335': 'consistency',
    'WPS336': 'consistency',
    'WPS337': 'consistency',
    'WPS338': 'consistency',
    'WPS339': 'consistency',
    'WPS340': 'consistency',
    'WPS341': 'consistency',
    'WPS342': 'consistency',
    'WPS343': 'consistency',
    'WPS344': 'consistency',
    'WPS345': 'consistency',
    'WPS346': 'consistency',
    'WPS347': 'consistency',
    'WPS348': 'consistency',
    'WPS349': 'consistency',
    'WPS350': 'consistency',
    'WPS351': 'consistency',
    'WPS352': 'consistency',
    'WPS353': 'consistency',
    'WPS354': 'consistency',
    'WPS355': 'consistency',
    'WPS356': 'consistency',
    'WPS357': 'consistency',
    'WPS358': 'consistency',
    'WPS359': 'consistency',
    'WPS360': 'consistency',
    'WPS361': 'consistency',
    'WPS362': 'consistency',
    'WPS363': 'consistency',
    'WPS364': 'consistency',
    'WPS365': 'consistency',
    'WPS366': 'consistency',
    'WPS400': 'best_practices',
    'WPS401': 'best_practices',
    'WPS402': 'best_practices',
    'WPS403': 'best_practices',
    'WPS404': 'best_practices',
    'WPS405': 'best_practices',
    'WPS406': 'best_practices',
    'WPS407': 'best_practices',
    'WPS408': 'best_practices',
    'WPS409': 'best_practices',
    'WPS410': 'best_practices',
    'WPS411': 'best_practices',
    'WPS412': 'best_practices',
    'WPS413': 'best_practices',
    'WPS414': 'best_practices',
    'WPS415': 'best_practices',
    'WPS416': 'best_practices',
    'WPS417': 'best_practices',
    'WPS418': 'best_practices',
    'WPS419': 'best_practices',
    'WPS420': 'best_practices',
    'WPS421': 'best_practices',
    'WPS422': 'best_practices',
    'WPS423': 'best_practices',
    'WPS424': 'best_practices',
    'WPS425': 'best_practices',
    'WPS426': 'best_practices',
    'WPS427': 'best_practices',
    'WPS428': 'best_practices',
    'WPS429': 'best_practices',
    'WPS430': 'best_practices',
    'WPS431': 'best_practices',
    'WPS432': 'best_practices',
    'WPS433': 'best_practices',
    'WPS434': 'best_practices',
    'WPS435': 'best_practices',
    'WPS436': 'best_practices',
    'WPS437': 'best_practices',
    'WPS438': 'best_practices',
    'WPS439': 'best_practices',
    'WPS440': 'best_practices',
    'WPS441': 'best_practices',
    'WPS442': 'best_practices',
    'WPS443': 'best_practices',
    'WPS444': 'best_practices',
    'WPS445': 'best_practices',
    'WPS446': 'best_practices',
    'WPS447': 'best_practices',
    'WPS448': 'best_practices',
    'WPS449': 'best_practices',
    'WPS450': 'best_practices',
    'WPS451': 'best_practices',
    'WPS452': 'best_practices',
    'WPS453': 'best_practices',
    'WPS454': 'best_practices',
    'WPS455': 'best_practices',
    'WPS456': 'best_practices',
    'WPS457': 'best_practices',
    'WPS458': 'best_practices',
    'WPS459': 'best_practices',
    'WPS460': 'best_practices',
    'WPS461': 'best_practices',
    'WPS462': 'best_practices',
    'WPS463': 'best_practices',
    'WPS464': 'best_practices',
    'WPS465': 'best_practices',
    'WPS466': 'best_practices',
    'WPS467': 'best_practices',
    'WPS468': 'best_practices',
    'WPS469': 'best_practices',
    'WPS470': 'best_practices',
    'WPS471': 'best_practices',
    'WPS472': 'best_practices',
    'WPS473': 'best_practices',
    'WPS474': 'best_practices',
    'WPS475': 'best_practices',
    'WPS476': 'best_practices',
    'WPS477': 'best_practices',
    'WPS478': 'best_practices',
    'WPS479': 'best_practices',
    'WPS480': 'best_practices',
    'WPS481': 'best_practices',
    'WPS500': 'refactoring',
    'WPS501': 'refactoring',
    'WPS502': 'refactoring',
    'WPS503': 'refactoring',
    'WPS504': 'refactoring',
    'WPS505': 'refactoring',
    'WPS506': 'refactoring',
    'WPS507': 'refactoring',
    'WPS508': 'refactoring',
    'WPS509': 'refactoring',
    'WPS510': 'refactoring',
    'WPS511': 'refactoring',
    'WPS512': 'refactoring',
    'WPS513': 'refactoring',
    'WPS514': 'refactoring',
    'WPS515': 'refactoring',
    'WPS516': 'refactoring',
    'WPS517': 'refactoring',
    'WPS518': 'refactoring',
    'WPS519': 'refactoring',
    'WPS520': 'refactoring',
    'WPS521': 'refactoring',
    'WPS522': 'refactoring',
    'WPS523': 'refactoring',
    'WPS524': 'refactoring',
    'WPS525': 'refactoring',
    'WPS526': 'refactoring',
    'WPS527': 'refactoring',
    'WPS528': 'refactoring',
    'WPS529': 'refactoring',
    'WPS530': 'refactoring',
    'WPS531': 'refactoring',
    'WPS532': 'refactoring',
    'WPS533': 'refactoring',
    'WPS534': 'refactoring',
    'WPS535': 'refactoring',
    'WPS536': 'refactoring',
    'WPS600': 'oop',
    'WPS601': 'oop',
    'WPS602': 'oop',
    'WPS603': 'oop',
    'WPS604': 'oop',
    'WPS605': 'oop',
    'WPS606': 'oop',
    'WPS607': 'oop',
    'WPS608': 'oop',
    'WPS609': 'oop',
    'WPS610': 'oop',
    'WPS611': 'oop',
    'WPS612': 'oop',
    'WPS613': 'oop',
    'WPS614': 'oop',
    'WPS615': 'oop',
    'WPS616': 'oop',
    'WPS617': 'oop',
}

